version: '3.8'

services:
  nginx:
    image: kelvinsilvadev/nginx:node
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://db:3306",
        "-timeout",
        "20s",
        "npm",
        "start"
      ]
    container_name: app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - ./app:/app
    networks:
      - node-network
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: db
    networks:
      - node-network
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:


networks:
  node-network:
    driver: bridge
